// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcyfazzyvrkybcljfdkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjeWZhenp5dnJreWJjbGpmZGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTM5NDIsImV4cCI6MjA2NjUyOTk0Mn0.eDWpdMcXfWKqPbSa_hitgsfibbHtDyNZrC3DqyP-bno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);